# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

language: rust
env:
  global:
  - PROJECT_NAME=clipivot
matrix:
  include:
  # Linux
  - env: TARGET=x86_64-unknown-linux-musl
    os: linux
  - env: TARGET=i686-unknown-linux-musl
    os: linux
  # OS-X
  # TODO: Get this working (currently fails because there isn't a `default-names` option in this Homebrew)
  # - env: TARGET=i686-apple-darwin
  #   os: osx
  - env: TARGET=x86_64-apple-darwin
    os: osx
  # Windows
  # TODO: Get this working (currently fails, possibly because Windows support new on Travis (but maybe not bc of that))
  # - env: TARGET=x86_64-pc-windows-gnu
  #   os: windows
  # - env: TARGET=x86_64-pc-windows-msvc
  #   os: windows
  # TODO: Get this working (currently fails, possibly bc of new Windows support for Travis)
  # - env: TARGET=i686-pc-windows-gnu
  #   os: windows
  # TODO: Get working (failed earlier bc couldn't find linker.exe)
  # - env: TARGET=i686-pc-windows-msvc

# adapted from https://github.com/BurntSushi/xsv/blob/master/.travis.yml
# with setup using `travis setup releases`
deploy:
  provider: releases
  api_key:
    secure: DBCJMy/GOJzRq/dMrv0alS+rb5OUJ10ToOSlFV939PNkXHE95eh9xuO+PaVOdr9HPk55bfPoGCwpkzMmkUy/Ru64L/DoNM7d4MiU0CxscRFh2L9B9cgIDoQb8/FgC/xRtVmybSQ93yBVIWjQjyX3hGYPAGcAdvBdb/0TTGmNb6EgcmR8OIh4oSgZ/3chUolGebAayXlfGhnKVx5NRwXBpEcz8UmXkct0j0t1IfHl22fI7/lUrPyVAUPStMwj1/eTRGhsMXHN7A1BDJaWRui0lr5NieTWn57i9azTVKbLTZSywp4qv2P8EdDPGVRW3HJOhMfOMDB3itLK8kgrhiPJOeY6rZHdlNg5pLF2SqJb67GqSdxvubcC89Yd8AkYmu+piFF1Yxvs2+rt1Gpc4dwhW55BuK3Gd0lzr7Cr4MR9sHsekMOE7XRx5B2QWX4R/oXbfWnJ4TVRmzD30QBkDRJJmPccdO64teZ/T5kUyDEZB9Du5x5RKLFG5AhESrf+CwG+EGH8YhoA1TcVBRgChtta7gAmyxWs5QPUIzswTGOS6sGdVm6h1Uvw+5TLo7V0PPkJyVUPsNhFgyVkfqiSNt2ui6T84aBsReDCzqv/i7WYmWd60aeaM8Aeb4SYrY+wZ6B2BeQDLjWKLrsNjOCecaa2IY3Ra/yLvVSNMHFqE1+yuZE=
  file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
  file_glob: true
  skip_cleanup: true
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    repo: maxblee/clipivot
    tags: true

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

# from https://github.com/BurntSushi/xsv/blob/master/.travis.yml
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/

notifications:
  email:
    on_success: never

# Everything below this from https://github.com/BurntSushi/xsv/blob/master/.travis.yml
before_install:
  - export PATH="$PATH:$HOME/.cargo/bin"

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

before_deploy:
  - sh ci/before_deploy.sh