[package]
name = "csvpivot"
version = "0.1.0"
authors = ["Max Lee <maxbmhlee@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://maxblee.github.io"
documentation = "https://maxblee.github.io/csvpivot"


[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
chrono = "0.4"
csv = "1"
serde = "1"
serde_derive = "1"

[dev-dependencies]
assert_cli = "0.6.3"
proptest = "0.9.4"